/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniMain */

#ifndef _Included_JniMain
#define _Included_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniMain
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniMain_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     JniMain
 * Method:    getStringFromC2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniMain_getStringFromC2
  (JNIEnv *, jobject);

/*
 * Class:     JniMain
 * Method:    accessFieldModify
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniMain_accessFieldModify
  (JNIEnv *, jobject);

/*
 * Class:     JniMain
 * Method:    accessStaticFieldModify
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniMain_accessStaticFieldModify
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
